{% set version = "0.8.27" %}

package:
  name: hdbscan
  version: {{ version }}

source:
  fn: hdbscan-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/h/hdbscan/hdbscan-{{ version }}.tar.gz
  sha256: e3a418d0d36874f7b6a1bf0b7461f3857fc13a525fd48ba34caed2fe8973aa26
build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - setuptools
    - scikit-learn >=0.16
    - cython >=0.17
    - joblib
    # 1.9 is the earliest for scikit-learn 0.16
    - numpy        # [not (win and (py35 or py36))]
    - numpy        # [win and py35]
    - numpy         # [win and py36]

  run:
    - python
    - scikit-learn >=0.16
    - joblib
    - six
    - {{ pin_compatible('numpy') }}   # [not (win and (py35 or py36))]
    - {{ pin_compatible('numpy') }}   # [win and py35]
    - {{ pin_compatible('numpy') }}   # [win and py36]

test:
  imports:
    - hdbscan

about:
  home: http://github.com/lmcinnes/hdbscan
  license: BSD 3-Clause
  license_file: LICENSE
  summary: Clustering based on density with variable density clusters

extra:
  recipe-maintainers:
    - lmcinnes
