{% set version = "0.8.32" %}

package:
  name: hdbscan
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/h/hdbscan/hdbscan-{{ version }}.tar.gz
  sha256: 2d80b371f3800d0f178540e3ec4474df54acd1c483e68a5121f4b0e15dac1e0b
build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - setuptools
    - scikit-learn >=0.16
    - cython >=0.17
    - joblib
    - numpy

  run:
    - python
    - scikit-learn >=0.16
    - joblib
    - six
    - cython >=0.17
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - hdbscan

about:
  home: http://github.com/lmcinnes/hdbscan
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Clustering based on density with variable density clusters

extra:
  recipe-maintainers:
    - johnlees
    - lmcinnes
