{% set version = "0.8.23" %}

package:
  name: hdbscan
  version: {{ version }}

source:
  fn: hdbscan-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/h/hdbscan/hdbscan-{{ version }}.tar.gz
  sha256: ff60c66591452ceb6bdb7592c560a1ebc7e128a02dd3880e048861f7fea7f78d

build:
  number: 0
  script:
    - source activate "${CONDA_DEFAULT_ENV}"  # [unix]
    - python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - setuptools
    - scikit-learn >=0.16
    - cython >=0.17
    - joblib
    # 1.9 is the earliest for scikit-learn 0.16
    - numpy        # [not (win and (py35 or py36))]
    - numpy        # [win and py35]
    - numpy         # [win and py36]

  run:
    - python
    - scikit-learn >=0.16
    - joblib
    - {{ pin_compatible('numpy') }}   # [not (win and (py35 or py36))]
    - {{ pin_compatible('numpy') }}   # [win and py35]
    - {{ pin_compatible('numpy') }}   # [win and py36]

test:
  imports:
    - hdbscan

about:
  home: http://github.com/lmcinnes/hdbscan
  license: BSD 3-Clause
  summary: 'Clustering based on density with variable density clusters'

extra:
  recipe-maintainers:
    - lmcinnes
