{% set version = "0.8.39" %}

package:
  name: hdbscan
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/h/hdbscan/hdbscan-{{ version }}.tar.gz
  sha256: 2aa1351f42fa79efdc47d53695381aa9a2efef6d1855b96c42d030646fee74f7

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython <4                              # [build_platform != target_platform]
    - numpy <3                               # [build_platform != target_platform]
    # Keep unconstrained for conda-smithy re-rendering
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler("c") }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - setuptools
    - wheel
    - cython <4
    - numpy <3
    # Keep unconstrained for conda-smithy re-rendering
    - numpy
  run:
    - python
    # Match upstream's `numpy` requirement and constraint
    - numpy <3,>=1.20
    - scipy >=1.0
    - scikit-learn >=0.20
    - joblib >=1.0

test:
  requires:
    - pip
  imports:
    - hdbscan
  commands:
    - pip check
    - python run_test.py

about:
  home: http://github.com/scikit-learn-contrib/hdbscan
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Clustering based on density with variable density clusters

extra:
  recipe-maintainers:
    - johnlees
    - lmcinnes
