{% set version = "0.8.43" %}

package:
  name: hdbscan
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/h/hdbscan/hdbscan-{{ version }}.tar.gz
  sha256: cfe6e7e68f153c92cef3d19a86d29c1075f33774b1e97d284ba79b157506c8bb

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython <4                              # [build_platform != target_platform]
    - numpy <3                               # [build_platform != target_platform]
    # Keep unconstrained for conda-smithy re-rendering
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler("c") }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - setuptools
    - wheel
    - cython <4
    - numpy <3
    # Keep unconstrained for conda-smithy re-rendering
    - numpy
  run:
    - python
    # Match upstream's `numpy` requirement and constraint
    - numpy >=1.20,<3
    - scipy >=1.0
    - scikit-learn >=1.6
    - joblib >=1.0

test:
  requires:
    - pip
  imports:
    - hdbscan
  commands:
    - pip check
    - python run_test.py

about:
  home: http://github.com/scikit-learn-contrib/hdbscan
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Clustering based on density with variable density clusters

extra:
  recipe-maintainers:
    - johnlees
    - lmcinnes
